FROM hahlabs/ubuntu:core
LABEL version.php="8.2.25" \
      version.zend="4.2.25" \
      version.ubuntu="22.04-lts" \
      version.grpc="1.68.0" \
      version.composer="2.8.3" \
      version.hahlabs-laravel="core-00.09.00" \
      version.description="Build for 22.04 & php8.2 - Laravel 10.x"


WORKDIR /home/hahlabs
COPY --chown=hahlabs:hahlabs files/. files/
USER root
RUN  apt -y update && apt -y upgrade \
    && files/install-tools.sh \
    && files/install-composer.sh \
    && files/build-grpc.sh \
    && cp files/startup.shams.sh /home/hahlabs/startup.sh 

USER hahlabs
# 80    : NGINX virtual host default: http://localhost:80 <-- removed
# 8201  : NGINX virtual host hahlabs app: http://localhost:8201
# 8222  : ssh 

# 9000 : php-fpm port -used internally - no need to expose
# 8210 : php artisan serve --host=0.0.0.0 --port=8210 || php -S 0.0.0.0:8210 
# 9003 : XDebugger, internal should not be exposed, VSCode will report port in use error if exposed
EXPOSE  8201
ENTRYPOINT sudo ./startup.sh  

