FROM hahlabs/mysql:shams
LABEL version.hahlabs-mysql="alpha-00.07.01"

COPY --chown=hahlabs:hahlabs files/. files/
USER root
RUN  apt -y update && apt -y upgrade && apt install -y net-tools vim\  
     && files/setup-ssh-server.sh 8022 \
     && cp files/startup.alpha.sh startup.sh \
     && rm -rf files 
     
     
USER hahlabs

EXPOSE 8022
# Enables the service on docker run container
ENTRYPOINT sudo ./startup.sh 