# Production Host only for the Angular Website no development tools
FROM hahlabs/ubuntu:core
LABEL version.ubuntu="22.04-lts" \
      version.node.js="20.10.0-lts" \
      version.hahlabs-angular="core-00.09.00" \
      version.description="Ubuntu 22.04 - NGINX"

COPY --chown=hahlabs:hahlabs files/. files/
# Update, Upgrade, install packages
USER root
RUN apt -y update && apt -y upgrade && apt install -y nginx \
    && cp files/startup.shams.sh /home/hahlabs/startup.sh \
    && rm -rf files
    
WORKDIR /home/hahlabs
USER hahlabs
# 8101 : NGINX with default virtual host to intial Angular project

EXPOSE 8101 
ENTRYPOINT sudo ./startup.sh 